version: "3.8"

services:
  e-voting-app:
    build: .
    container_name: e-voting-app
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./src:/app/src
    networks:
      - my_network
    user: "1000:1000"

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - /etc/ssl/api.usn-vote.space:/etc/nginx/ssl:ro
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "envsubst '$$SERVER_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'",
      ]
    depends_on:
      - e-voting-app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  pgdata:
