version: "3.8"

services:
  e-voting-app:
    build: ./e-voting-app
    container_name: e-voting-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      postgres_evoting_app:
        condition: service_healthy
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_evoting_app:5432/${POSTGRES_DB}
    volumes:
      - ./src:/app/src
    networks:
      - shared_network
    user: "1000:1000"

  postgres_evoting_app:
    image: postgres:latest
    container_name: postgres-evoting-app
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_e_voting_app:/var/lib/postgresql/data
    networks:
      - shared_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

volumes:
  pgdata_e_voting_app:
    driver: local

networks:
  shared_network:
    external: true
    name: shared_network
